version: "3.9"

services:
  backend:
    build:
      context: ./backend-go
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "3010:80"
    depends_on:
      - backend
